# -*- coding: utf-8 -*-
"""ML_Assignment_EDA_LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndWlMq-cltUJz_0bmoF_pJrxsOTJ6p9I

# Introduction to Machine Learning
## Assignment-I / Project-I
### Task-1: Exploratory Data Analysis (EDA) + Linear Regression
**Dataset:** COVID-19 Health Dataset  
**Tools:** Python, Pandas, Matplotlib, Seaborn, Scikit-learn

---
"""

# Install required libraries (uncomment if running on Colab/Kaggle)
# !pip install pandas numpy matplotlib seaborn scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# Plot style
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette('husl')

print('✅ All libraries imported successfully!')

"""## 📂 Step 2: Load COVID-19 Dataset
We use the **Our World in Data** COVID-19 dataset — publicly available and health-related.
"""

url = "https://raw.githubusercontent.com/datasets/covid-19/main/data/countries-aggregated.csv"
df_raw = pd.read_csv(url)
print(f"✅ Dataset loaded! Shape: {df_raw.shape}")
df_raw.head()

df_raw['Date'] = pd.to_datetime(df_raw['Date'])
df = df_raw.groupby('Country').last().reset_index()

# Columns rename karo
df.columns = ['country', 'date', 'confirmed', 'recovered', 'deaths']

# Death rate column add karo
df['death_rate'] = (df['deaths'] / df['confirmed']) * 100
df['recovery_rate'] = (df['recovered'] / df['confirmed']) * 100

# Missing values remove karo
df = df[(df['confirmed'] > 0) & (df['deaths'] > 0)]

print(f"✅ Clean dataset shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
df.head(10)

# ============================================
# Step 4: EDA - Basic Info
# ============================================
print("="*50)
print("DATASET INFO:")
print(df.dtypes)
print("\nBASIC STATISTICS:")
print(df.describe())
print(f"\nMissing values: {df.isnull().sum().sum()}")

# ============================================
# Step 5: EDA - Visualizations
# ============================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Top 10 countries by cases
top10 = df.nlargest(10, 'confirmed')
axes[0,0].barh(top10['country'], top10['confirmed']/1e6, color='steelblue')
axes[0,0].set_title('Top 10 Countries - Confirmed Cases (M)', fontweight='bold')
axes[0,0].set_xlabel('Cases (Millions)')

# Top 10 by deaths
axes[0,1].barh(top10['country'], top10['deaths']/1e3, color='coral')
axes[0,1].set_title('Top 10 Countries - Deaths (K)', fontweight='bold')
axes[0,1].set_xlabel('Deaths (Thousands)')

# Death rate distribution
axes[1,0].hist(df['death_rate'], bins=30, color='orange', edgecolor='black')
axes[1,0].set_title('Death Rate Distribution (%)', fontweight='bold')
axes[1,0].set_xlabel('Death Rate %')

# Confirmed vs Deaths scatter
axes[1,1].scatter(df['confirmed']/1e6, df['deaths']/1e3, alpha=0.6, color='purple', s=30)
axes[1,1].set_title('Confirmed Cases vs Deaths', fontweight='bold')
axes[1,1].set_xlabel('Confirmed (M)')
axes[1,1].set_ylabel('Deaths (K)')

plt.tight_layout()
plt.show()

# ============================================
# Step 6: Correlation Heatmap
# ============================================
corr = df[['confirmed','deaths','recovered','death_rate','recovery_rate']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

# ============================================
# Step 7: Simple Linear Regression
# Confirmed Cases se Deaths predict karna
# ============================================
X = df[['confirmed']]
y = df['deaths']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

slr = LinearRegression()
slr.fit(X_train, y_train)
y_pred = slr.predict(X_test)

print("="*45)
print("   SIMPLE LINEAR REGRESSION RESULTS")
print("="*45)
print(f"  Intercept  : {slr.intercept_:.4f}")
print(f"  Coefficient: {slr.coef_[0]:.6f}")
print(f"  R² Score   : {r2_score(y_test, y_pred):.4f}")
print(f"  RMSE       : {np.sqrt(mean_squared_error(y_test, y_pred)):,.2f}")
print(f"  MAE        : {mean_absolute_error(y_test, y_pred):,.2f}")
print("="*45)

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].scatter(X_test, y_test, alpha=0.5, color='steelblue', s=20, label='Actual')
axes[0].plot(sorted(X_test['confirmed']), slr.predict(pd.DataFrame(sorted(X_test['confirmed']), columns=['confirmed'])), color='red', lw=2, label='Regression Line')
axes[0].set_title('Simple LR: Cases → Deaths', fontweight='bold')
axes[0].set_xlabel('Confirmed Cases')
axes[0].set_ylabel('Deaths')
axes[0].legend()

axes[1].scatter(y_test, y_pred, alpha=0.5, color='green', s=20)
axes[1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
axes[1].set_title(f'Actual vs Predicted\nR²={r2_score(y_test,y_pred):.4f}', fontweight='bold')
axes[1].set_xlabel('Actual Deaths')
axes[1].set_ylabel('Predicted Deaths')
plt.tight_layout()
plt.show()

# ============================================
# Step 8: Multiple Linear Regression
# ============================================
X_multi = df[['confirmed', 'recovered', 'death_rate', 'recovery_rate']]
y_multi = df['deaths']

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train_m)
X_test_s  = scaler.transform(X_test_m)

mlr = LinearRegression()
mlr.fit(X_train_s, y_train_m)
y_pred_m = mlr.predict(X_test_s)

print("="*45)
print("  MULTIPLE LINEAR REGRESSION RESULTS")
print("="*45)
print(f"  R² Score   : {r2_score(y_test_m, y_pred_m):.4f}")
print(f"  RMSE       : {np.sqrt(mean_squared_error(y_test_m, y_pred_m)):,.2f}")
print(f"  MAE        : {mean_absolute_error(y_test_m, y_pred_m):,.2f}")
print("\n  Feature Coefficients:")
for f, c in zip(X_multi.columns, mlr.coef_):
    print(f"    {f:20s}: {c:.4f}")
print("="*45)

# Coefficient plot
plt.figure(figsize=(8, 4))
colors = ['green' if c > 0 else 'red' for c in mlr.coef_]
plt.barh(list(X_multi.columns), mlr.coef_, color=colors, edgecolor='black')
plt.axvline(0, color='black', lw=0.8)
plt.title('Feature Coefficients - Multiple LR', fontweight='bold')
plt.xlabel('Coefficient Value')
plt.tight_layout()
plt.show()

# ============================================
# Step 9: Model Comparison
# ============================================
results = pd.DataFrame({
    'Model'   : ['Simple LR', 'Multiple LR'],
    'R² Score': [round(r2_score(y_test, y_pred), 4),
                 round(r2_score(y_test_m, y_pred_m), 4)],
    'RMSE'    : [round(np.sqrt(mean_squared_error(y_test, y_pred)), 2),
                 round(np.sqrt(mean_squared_error(y_test_m, y_pred_m)), 2)],
    'MAE'     : [round(mean_absolute_error(y_test, y_pred), 2),
                 round(mean_absolute_error(y_test_m, y_pred_m), 2)],
})
print(results.to_string(index=False))

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].bar(['Simple LR','Multiple LR'], results['R² Score'], color=['steelblue','darkorange'], edgecolor='black')
axes[0].set_title('R² Score (Higher = Better)', fontweight='bold')
axes[0].set_ylim(0, 1)

axes[1].bar(['Simple LR','Multiple LR'], results['RMSE'], color=['steelblue','darkorange'], edgecolor='black')
axes[1].set_title('RMSE (Lower = Better)', fontweight='bold')

plt.tight_layout()
plt.show()

print("\n✅ Assignment Complete!")

"""---
**Assignment Completed By:** *( Syeda Fatima)*  
**Course:** Introduction to Machine Learning  
**Dataset:** COVID-19 - Our World in Data  
**Submission Date:** March 2026
"""